name: Update Docs

on:
  release:
    types:
      - created

jobs:
  build:
    name: Update Docs (pkg.go.dev)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: Pull latest version
        run: |
          go mod init tmp

          version=${GITHUB_REF#refs/*/}
          
          submodules=$(dirname $(find . -mindepth 2 -maxdepth 2 -name 'go.mod'))


          for submodule in $submodules; do
            path=github.com/mr-linch/go-tg-store/${submodule/.\//}@${version}
            echo "Updating $path"
            go get "$path"
          done